# Generated by Django 5.0.4 on 2024-04-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0003_us_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='stories',
                related_query_name='story',
                to='epics.contributor'),
        ),
    ]
