"""
This file was auto-generated by djelm 0.10.0

For the best developer experience ensure the following:

- EpicFlags variable is not renamed.
- The key variable value "frontendepic-djelmwidget-Epic" is not modified
"""

from djelm.flags import Flags, ListFlag, StringFlag, ObjectFlag

key = "frontendepic-djelm-Epic"

EpicFlags = Flags(
     ObjectFlag(
         {
             "epic": ObjectFlag(
                 {
                     "title": StringFlag(),
                     "pubDate": StringFlag(),
                     "description": StringFlag(),
                     "ownerFullname": StringFlag(),
                     "stories": ListFlag(
                         ObjectFlag(
                             {
                                 "title": StringFlag(),
                                 "description": StringFlag(),
                                 "status": StringFlag(),
                             }
                         )
                     )
                 }
             ),
             "logoutUrl": StringFlag(),
             "csrfToken": StringFlag(),
         }
     )
)
