"""
This file was auto-generated by djelm 0.10.0

For the best developer experience ensure the following:

- LandingFlags variable is not renamed.
- The key variable value "frontendlanding-djelmwidget-Landing" is not modified
"""

from djelm.flags import (
    BoolFlag,
    Flags,
    ListFlag,
    NullableFlag,
    ObjectFlag,
    StringFlag,
)

key = "frontendlanding-djelm-Landing"

LandingFlags = Flags(
    ObjectFlag(
        {
            "userInfo": ObjectFlag(
                {
                    "fullname": StringFlag(),
                    "name": StringFlag(),
                    "firstName": NullableFlag(StringFlag()),
                    "lastName": NullableFlag(StringFlag()),
                    "email": NullableFlag(StringFlag()),
                    "isStaff": BoolFlag(),
                }
            ),
            "csrfToken": StringFlag(),
            "logoutUrl": StringFlag(),
            "epics": ListFlag(
                ObjectFlag(
                    {
                        "title": StringFlag(),
                        "pubDate": StringFlag(),
                        "description": StringFlag(),
                        "ownerFullname": StringFlag(),
                        "owner": StringFlag(),
                        "url": StringFlag(),
                    }
                )
            )
        }
    )
)
