"""
This file was auto-generated by djelm 0.10.0

For the best developer experience ensure the following:

- LandingFlags variable is not renamed.
- The key variable value "frontendlanding-djelmwidget-Landing" is not modified
"""

from djelm.flags import Flags, NullableFlag, ObjectFlag, StringFlag, BoolFlag

key = "frontendlanding-djelm-Landing"

LandingFlags = Flags(
    ObjectFlag(
        {
            "fullname": StringFlag(),
            "firstName": NullableFlag(StringFlag()),
            "lastName": NullableFlag(StringFlag()),
            "email": NullableFlag(StringFlag()),
            "isStaff": BoolFlag(),
            "csrfToken": StringFlag(),
            "logoutUrl": StringFlag(),
        }
    )
)
