"""
This file was auto-generated by djelm 0.11.0

For the best developer experience ensure the following:

- StoryFlags variable is not renamed.
- The key variable value "frontendstory-djelmwidget-Story" is not modified
"""
from djelm.flags import (
    Flags,
    ListFlag,
    StringFlag,
    ObjectFlag,
    NullableFlag,
    IntFlag,
)

key = "frontendstory-djelm-Story"

StoryFlags = Flags(
    ObjectFlag(
        {
            "story": ObjectFlag(
                {
                    "id": IntFlag(),
                    "pubDate": StringFlag(),
                    "title": StringFlag(),
                    "description": StringFlag(),
                    "status": StringFlag(),
                    "assignedTo": NullableFlag(StringFlag()),
                    "assignedToFullname": NullableFlag(StringFlag()),
                }
            ),
            "logoutUrl": StringFlag(),
            "csrfToken": StringFlag(),
            "username": StringFlag(),
        }
    )
)
