# Generated by Django 5.0.4 on 2024-04-27 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epics", "0003_us_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("in progress", "In Progress"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                            ("finished", "Finished"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="epics.userstory",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="epics.contributor",
                    ),
                ),
            ],
        ),
    ]
