# Generated by Django 5.0.4 on 2024-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial_status_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuschange",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
