# Generated by Django 5.0.4 on 2024-04-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_add_duration_status_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
