module Models.Epic exposing (..)

{-| Do not manually edit this file, it was auto-generated by djelm
<https://github.com/Confidenceman02/django-elm>
-}

import Json.Decode as Decode
import Json.Decode.Pipeline exposing (required, optional, hardcoded)


type alias ToModel =
    { title : String
    , pubDate : String
    , description : String
    , ownerFullname : String
    }


toModel : Decode.Decoder ToModel
toModel =
    Decode.succeed ToModel
        |> required "title" Decode.string
        |> required "pubDate" Decode.string
        |> required "description" Decode.string
        |> required "ownerFullname" Decode.string
