module Models.Landing exposing (..)

{-| Do not manually edit this file, it was auto-generated by djelm
<https://github.com/Confidenceman02/django-elm>
-}

import Json.Decode as Decode
import Json.Decode.Pipeline exposing (required, optional, hardcoded)


type alias ToModel =
    { userInfo : UserInfo_
    , csrfToken : String
    , logoutUrl : String
    , epics : Epics_
    }

type alias UserInfo_ =
    { fullname : String
    , name : String
    , firstName : Maybe String
    , lastName : Maybe String
    , email : Maybe String
    , isStaff : Bool
    }

type alias Epics_ =
    { url : String }


toModel : Decode.Decoder ToModel
toModel =
    Decode.succeed ToModel
        |> required "userInfo" userInfo_Decoder
        |> required "csrfToken" Decode.string
        |> required "logoutUrl" Decode.string
        |> required "epics" epics_Decoder

userInfo_Decoder : Decode.Decoder UserInfo_
userInfo_Decoder =
    Decode.succeed UserInfo_
        |> required "fullname" Decode.string
        |> required "name" Decode.string
        |> required "firstName" (Decode.nullable Decode.string)
        |> required "lastName" (Decode.nullable Decode.string)
        |> required "email" (Decode.nullable Decode.string)
        |> required "isStaff" Decode.bool

epics_Decoder : Decode.Decoder Epics_
epics_Decoder =
    Decode.succeed Epics_
        |> required "url" Decode.string
