module Models.Story exposing (..)

{-| Do not manually edit this file, it was auto-generated by djelm
<https://github.com/Confidenceman02/django-elm>
-}

import Json.Decode as Decode
import Json.Decode.Pipeline exposing (required, optional, hardcoded)


type alias ToModel =
    { story : Story_
    , logoutUrl : String
    , csrfToken : String
    , username : String
    }

type alias Story_ =
    { id : Int
    , pubDate : String
    , title : String
    , description : String
    , status : String
    , assignedTo : Maybe String
    , assignedToFullname : Maybe String
    }


toModel : Decode.Decoder ToModel
toModel =
    Decode.succeed ToModel
        |> required "story" story_Decoder
        |> required "logoutUrl" Decode.string
        |> required "csrfToken" Decode.string
        |> required "username" Decode.string

story_Decoder : Decode.Decoder Story_
story_Decoder =
    Decode.succeed Story_
        |> required "id" Decode.int
        |> required "pubDate" Decode.string
        |> required "title" Decode.string
        |> required "description" Decode.string
        |> required "status" Decode.string
        |> required "assignedTo" (Decode.nullable Decode.string)
        |> required "assignedToFullname" (Decode.nullable Decode.string)
